### ISSUE TITLE
Any chance on updating to 2018.3 and Entities preview 23?

### ISSUE THREAD

**Issue by MostHated** [BuildingBetterGames/AISystem#1]
Hey there,
    I just came across this system and it looks rather interesting. Is there any chance that you might be thinking about updating it to the newer API? There were a few nice but rather important changes. Such as a new hybrid renderer which removes MeshInstanceRendererComponent and replaces with RenderMeshComponent, depreciation if [inject] and replacement with a better system, and things of that nature. I would very much love to try and study this a bit using the newer API as I am getting my feet wet with ECS / Jobs and this is exactly the type of thing I would like to learn it for.

Thanks!
-MH

**Comment by BuildingBetterGames** [comment]
Sorry about the late reply, I updated it to 2018.3
I'm going to more on this in the next couple weeks, hopefully I'll add combat AI.
